# Generated by Django 2.2.1 on 2019-06-12 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=20, null=True)),
                ('label', models.CharField(max_length=100, null=True)),
                ('artist', models.CharField(max_length=100, null=True)),
                ('music_name', models.CharField(max_length=100, null=True)),
                ('music_path', models.FileField(upload_to='songs/%Y/%m/%d/')),
                ('file_ext', models.CharField(max_length=10, null=True)),
                ('label_image', models.ImageField(default='music_labels/default_label.jpg', upload_to='music_labels/')),
                ('artist_image', models.ImageField(default='artists/default_artist.jpg', upload_to='artists/')),
                ('release_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
