# Generated by Django 2.2.1 on 2019-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
