# Generated by Django 2.2.1 on 2019-06-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist_image',
            field=models.ImageField(default='music/artists/default_artist.jpg', upload_to='music/artists/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='label_image',
            field=models.ImageField(default='music/labels/default_label.jpg', upload_to='music/labels/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_path',
            field=models.FileField(upload_to='music/songs/%Y/%m/%d/'),
        ),
    ]
