# Generated by Django 2.2.1 on 2019-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190612_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='reference_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
