# Generated by Django 2.2.1 on 2019-06-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='category',
            field=models.CharField(choices=[('Android', 'android'), ('Games', 'games'), ('OS', 'os'), ('PC', 'pc')], max_length=10, null=True),
        ),
    ]
