# Generated by Django 2.2.1 on 2019-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0002_auto_20190612_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, null=True),
        ),
    ]
