# Generated by Django 2.2.1 on 2019-06-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date_deleted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
