# Generated by Django 2.2.1 on 2019-06-10 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190610_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date_deleted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
