# Generated by Django 2.2.1 on 2019-06-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/user_avatar.png', upload_to='avatars/'),
        ),
    ]
