# Generated by Django 2.2.1 on 2019-06-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190613_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shipping_addr',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
