# Generated by Django 2.2.1 on 2019-06-24 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import food_drink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LCL', 'Local'), ('INTL', 'International')], max_length=20, null=True)),
                ('ref_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('ingredients', models.TextField(max_length=500, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('assoc_country', models.CharField(choices=[('NG', 'Nigeria')], max_length=20)),
                ('assoc_states', models.CharField(choices=[('ABA', 'Abia'), ('EN', 'Enugu'), ('LG', 'Lagos')], max_length=20)),
                ('image_rep', models.ImageField(upload_to=food_drink.models.format_food_drink_img_path)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDrinkReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_drink.FoodDrink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
