# Generated by Django 2.2.1 on 2019-06-24 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0021_country_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('ref_id', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(choices=[('LCL', 'Local'), ('INTL', 'International')], max_length=20, null=True)),
                ('has_extras', models.BooleanField(default=False)),
                ('can_book', models.BooleanField(default=False)),
                ('can_place_order', models.BooleanField(default=False)),
                ('can_make_home_delivery', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=100, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('image_rep', models.ImageField(upload_to=restaurant.models.format_restaurant_img_path)),
                ('date_history', models.DateField(null=True)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.Country')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.State')),
            ],
        ),
    ]
