# Generated by Django 2.2.1 on 2019-06-24 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190624_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Country'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.State'),
        ),
    ]
