# Generated by Django 2.2.1 on 2019-06-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20190624_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(choices=[('NG', 'Nigeria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(choices=[('ABA', 'Abia'), ('EN', 'Enugu'), ('LG', 'Lagos')], max_length=20),
        ),
    ]
