# Generated by Django 2.2.1 on 2019-06-24 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0005_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='RestaurantReview',
        ),
    ]
