# Generated by Django 2.2.1 on 2019-06-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20190624_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mail',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
