# Generated by Django 2.2.1 on 2019-07-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20190627_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
