# Generated by Django 2.2.1 on 2019-07-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20190717_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='ref_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
