# Generated by Django 2.2.1 on 2019-06-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190612_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
