# Generated by Django 2.2.1 on 2019-06-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_info_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='post_image',
            field=models.ImageField(default='info/images/default_info.jpg', upload_to='info/images/'),
        ),
    ]
