# Generated by Django 2.2.1 on 2019-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_info_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='visits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
