# Generated by Django 2.2.1 on 2019-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('E', 'Error'), ('N', 'Normal')], max_length=10, null=True),
        ),
    ]
