# Generated by Django 2.2.1 on 2019-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190610_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
