# Generated by Django 2.2.1 on 2019-06-10 14:31

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_userprofile_is_super'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(default=index.models.UserProfile, max_length=20, null=True),
        ),
    ]
