# Generated by Django 2.2.1 on 2019-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190610_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(default="<class 'index.models.UserProfile'>", max_length=20, null=True),
        ),
    ]
