# Generated by Django 2.2.1 on 2019-06-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20190611_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('TYPE_A', 'type_A'), ('TYPE_B', 'type_B')], max_length=10, null=True),
        ),
    ]
