# Generated by Django 2.2.1 on 2019-06-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
