# Generated by Django 2.2.1 on 2019-06-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='salt',
        ),
    ]
