# Generated by Django 2.2.1 on 2019-06-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20190624_0157'),
        ('index', '0022_auto_20190624_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
