# Generated by Django 2.2.1 on 2019-06-24 20:03

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20190624_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(upload_to=index.models.format_all_img_path)),
            ],
        ),
    ]
