# Generated by Django 2.2.1 on 2019-06-24 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_imagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
