# Generated by Django 2.2.1 on 2019-06-24 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import event_center.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('ref_id', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(choices=[('LCL', 'Local'), ('INTL', 'International')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('website', models.CharField(max_length=50, null=True)),
                ('can_book', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=100, null=True)),
                ('availability', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('country', models.CharField(choices=[('NG', 'Nigeria')], max_length=20)),
                ('state', models.CharField(choices=[('ABA', 'Abia'), ('EN', 'Enugu'), ('LG', 'Lagos')], max_length=20)),
                ('image_rep', models.ImageField(upload_to=event_center.models.format_event_img_path)),
                ('date_history', models.DateField(null=True)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCenterReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_center.EventCenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
