# Generated by Django 2.2.1 on 2019-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcenter',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
