# Generated by Django 2.2.1 on 2019-06-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_center', '0002_auto_20190626_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcenter',
            name='website',
            field=models.CharField(default='no website', max_length=50, null=True),
        ),
    ]
